/** Curated metadata merged onto Wikipedia-parsed inventions by wikipedia title. */

export const TIER1 = new Map([
  ['Stone tool', { tier: 1, categories: ['survival'], description: 'Earliest known flaked stone tools, including finds from Kenya (Lomekwi) and later Oldowan tools from Ethiopia. Dates mark archaeological evidence and can change as new discoveries are made.', significance: 'Flaked stone is the earliest durable evidence of technological culture. Later industries rest on this capacity to shape materials on purpose.', related: ['Control of fire by early humans', 'Acheulean'] }],
  ['Control of fire by early humans', { tier: 1, title: 'Control of fire', categories: ['survival', 'energy'], significance: 'Fire extended the day, changed diet through cooking, and became a tool for heat, light, and later metallurgy. Early dates are archaeological estimates and remain debated.', related: ['Cooking', 'Pottery'] }],
  ['Cooking', { tier: 1, categories: ['survival', 'agriculture'], significance: 'Cooking increased the usable energy in food and is tightly linked to fire control. Dates are inferred from archaeology and remain uncertain.' }],
  ['Agriculture', { tier: 1, categories: ['agriculture'], significance: 'Farming made food surplus, denser settlement, and specialist crafts possible. It arose independently in several regions; Wikipedia dates the Fertile Crescent evidence around 10,000–9,000 BCE.', related: ['Domestication of the sheep', 'Irrigation', 'Plough'] }],
  ['Domestication of the sheep', { tier: 1, title: 'Animal domestication', categories: ['agriculture'], significance: 'Domestic animals supplied meat, fiber, labor, and later transport. Sheep are among the earliest clearly documented cases in Southwest Asia.' }],
  ['Writing', { tier: 1, categories: ['communication'], significance: 'Writing made administration, law, literature, and cumulative science possible beyond living memory.', related: ['Papyrus', 'Paper', 'Printing press'] }],
  ['Wheel', { tier: 1, categories: ['transportation'], significance: 'Wheeled vehicles and later machinery depend on rotation under load. The oldest surviving wooden wheel is far later than the idea of the wheel itself.', related: ['Chariot', 'Railroad'] }],
  ['Ljubljana Marshes Wheel', { tier: 1, title: 'Wooden wheel', categories: ['transportation'], significance: 'The oldest known surviving wooden wheel, from Slovenia, is direct evidence of wheeled technology in the fourth millennium BCE.' }],
  ['City', { tier: 1, title: 'Cities', categories: ['construction'], significance: 'Urban concentration created specialist labor, monumental building, and the administrative problems that writing later solved.' }],
  ['Paper', { tier: 1, categories: ['communication'], significance: 'Paper became a cheap, portable writing surface and later the substrate of print culture.', related: ['Writing', 'Printing press'] }],
  ['Printing press', { tier: 1, categories: ['communication'], inventor: ['Johannes Gutenberg'], significance: 'Movable-type printing multiplied texts and accelerated the spread of knowledge, religion, science, and news in Europe.', related: ['Paper', 'Newspaper', 'Internet'] }],
  ['Steam engine', { tier: 1, categories: ['energy', 'transportation'], significance: 'A practical heat engine converted fossil energy into continuous mechanical work and powered factories, mines, and railways.', related: ['Railroad', 'Factory'] }],
  ['Telephone', { tier: 1, categories: ['communication'], inventor: ['Alexander Graham Bell'], significance: 'Speech at a distance collapsed the time of conversation. Several inventors worked on the problem; Bell received a key 1876 patent.', related: ['Telegraphy', 'Radio', 'Smartphone'] }],
  ['Incandescent light bulb', { tier: 1, title: 'Electric light', categories: ['energy'], inventor: ['Joseph Swan', 'Thomas Edison'], significance: 'Electric lighting decoupled work and public life from daylight and became a symbol of electrification.', related: ['Electrical generator'] }],
  ['Car', { tier: 1, title: 'Automobile', categories: ['transportation'], significance: 'Powered personal vehicles remade cities, work, and the geography of daily life.', related: ['Internal combustion engine'] }],
  ['Airplane', { tier: 1, categories: ['transportation'], inventor: ['Wright brothers'], significance: 'Controlled powered flight opened a third dimension of transport and later global travel.', related: ['Jet engine'] }],
  ['Transistor', { tier: 1, categories: ['computing', 'energy'], significance: 'A solid-state switch made electronics small, reliable, and mass-producible — the seed of the digital revolution.', related: ['Integrated circuit', 'Microprocessor'] }],
  ['Integrated circuit', { tier: 1, categories: ['computing'], significance: 'Putting many transistors on one chip made computers cheap enough to leave the laboratory.', related: ['Transistor', 'Microprocessor'] }],
  ['Microprocessor', { tier: 1, categories: ['computing'], significance: 'A computer on a chip made personal computing, embedded control, and later smartphones possible.', related: ['Personal computer', 'Internet'] }],
  ['Internet', { tier: 1, categories: ['computing', 'communication'], significance: 'A general-purpose packet network became the substrate for almost every later digital invention.', related: ['ARPANET', 'World Wide Web'] }],
  ['World Wide Web', { tier: 1, categories: ['computing', 'communication'], inventor: ['Tim Berners-Lee'], significance: 'A shared hypertext layer made the internet usable as a public information space.', related: ['Internet', 'Search engine'] }],
  ['Smartphone', { tier: 1, categories: ['computing', 'communication'], significance: 'A pocket computer with a network connection moved computing into everyday life.', related: ['Internet', 'World Wide Web'] }],
  ['Vaccination', { tier: 1, categories: ['medicine'], inventor: ['Edward Jenner'], significance: 'Deliberate immunization against smallpox became the model for preventing infectious disease.', related: ['Antibiotics'] }],
  ['Antibiotics', { tier: 1, categories: ['medicine'], significance: 'Drugs that kill or stop bacteria transformed infection from a common cause of death into a treatable condition.' }],
  ['Penicillin', { tier: 1, categories: ['medicine'], inventor: ['Alexander Fleming'], significance: 'The first widely used antibiotic opened modern infectious-disease medicine.' }],
  ['Nuclear reactor', { tier: 1, categories: ['energy', 'science'], significance: 'A controlled chain reaction showed that nuclear energy could be harnessed, for power as well as weapons.' }],
  ['Satellite', { tier: 1, categories: ['transportation', 'communication'], significance: 'Artificial satellites made planetary observation, navigation, and global communication routine.' }],
  ['Sputnik 1', { tier: 1, title: 'Orbital satellite', categories: ['transportation', 'science'], significance: 'The first artificial satellite opened the Space Age and proved that machines could stay in Earth orbit.' }],
  ['Wright Flyer', { tier: 1, title: 'Powered airplane', categories: ['transportation'], inventor: ['Wright brothers'], significance: 'Controlled powered flight opened a third dimension of transport and later global travel.' }],
  ['Newcomen atmospheric engine', { tier: 1, title: 'Steam engine', categories: ['energy'], inventor: ['Thomas Newcomen'], significance: 'A practical heat engine converted fossil energy into continuous mechanical work and powered mines, then factories and railways.' }],
  ['Watt steam engine', { tier: 1, title: 'Watt steam engine', categories: ['energy'], inventor: ['James Watt'], significance: 'A more efficient steam engine made rotary factory power practical and helped launch industrial production.' }],
])

export const TIER2_TITLES = new Set([
  'Acheulean',
  'Bone tool',
  'Hafting',
  'Clothing',
  'Sewing needle',
  'Pottery',
  'Ceramics',
  'Bow and arrow',
  'Arrow',
  'Irrigation',
  'Plough',
  'Bronze',
  'Iron',
  'Glass',
  'Concrete',
  'Papyrus',
  'Alphabet',
  'Coin',
  'Compass',
  'Gunpowder',
  'Mechanical clock',
  'Telescope',
  'Microscope',
  'Spinning jenny',
  'Power loom',
  'Railroad',
  'Locomotive',
  'Photography',
  'Telegraphy',
  'Electrical generator',
  'Internal combustion engine',
  'Radio',
  'Cinema',
  'Assembly line',
  'Jet engine',
  'Electronic computer',
  'Computer',
  'ARPANET',
  'Personal computer',
  'GPS',
  'Email',
  'Search engine',
  'Deep learning',
  'Transformer (deep learning architecture)',
  'ChatGPT',
  'Large language model',
  'Anaesthesia',
  'Anesthesia',
  'X-ray',
  'DNA',
  'Steel',
  'Stainless steel',
  'Plastic',
  'Polyvinyl chloride',
  'Dynamite',
  'Oil well',
  'Light-emitting diode',
  'Laser',
  'Television',
  'Phonograph',
  'Four-stroke cycle',
  'Hot air balloon',
  'Steamboat',
  'Piano',
  'Movable type',
  'Woodblock printing',
  'Stirrup',
  'Horse collar',
  'Windmill',
  'Watermill',
  'Aqueduct',
  'Road',
  'Sail',
  'Chariot',
  'Sword',
  'Calendar',
  'Zero',
  'Algebra',
  'Printing',
  'Newspaper',
  'Battery (electricity)',
  'Electric battery',
  'Leyden jar',
  'Refrigeration',
  'Pasteurization',
  'Periodic table',
  'Radioactivity',
  'Quantum mechanics',
  'Relativity',
  'ENIAC',
  'UNIX',
  'Linux',
  'Packet switching',
  'Ethernet',
  'Graphical user interface',
  'World Wide Web Consortium',
  'IBM Simon',
  'Touchscreen',
  'Machine learning',
  'AlexNet',
  'CRISPR',
  'mRNA vaccine',
  'COVID-19 vaccine',
])

export const TITLE_FIXES = new Map([
  ['Control of fire by early humans', 'Control of fire'],
  ['Domestication of the sheep', 'Sheep domestication'],
  ['History of clothing and textiles', 'Clothing'],
  ['History of hide materials', 'Hide clothing'],
  ['Stone tool', 'Stone tools'],
  ['Ljubljana Marshes Wheel', 'Wooden wheel'],
  ['Incandescent light bulb', 'Incandescent lamp'],
  ['Car', 'Automobile'],
  ['IBM Simon', 'Smartphone'],
])

export const SIGNIFICANCE = new Map([
  ['Telescope', 'Opened the sky as a measurable object and helped establish observational astronomy.'],
  ['Microscope', 'Revealed a living world below the limit of the unaided eye.'],
  ['Gunpowder', 'A chemical energy store that remade warfare and later mining and engineering.'],
  ['Compass', 'Reliable direction-finding made open-ocean navigation more practical.'],
  ['Railroad', 'Steam on rails created the first high-capacity overland transport network.'],
  ['Photography', 'Light could be stored. Memory, journalism, science, and art all changed.'],
  ['Radio', 'Information without wires. News, entertainment, and later digital data followed.'],
  ['Internal combustion engine', 'A compact heat engine that made automobiles and aircraft practical.'],
  ['Concrete', 'A pourable stone that let Romans — and later modern cities — build at civic scale.'],
  ['Iron', 'A common metal that made tools and weapons cheaper than bronze in many regions.'],
  ['Bronze', 'An alloy harder than copper, used for tools, weapons, and prestige objects.'],
  ['Papyrus', 'A light writing sheet that helped administration and literature in Egypt and the Mediterranean.'],
  ['Alphabet', 'A small set of signs for sounds made writing easier to learn than earlier systems.'],
  ['ChatGPT', 'A public large-language-model interface made generative AI a mass-market tool.'],
  ['AlexNet', 'A 2012 neural-network result that helped restart large-scale deep learning.'],
  ['ARPANET', 'A packet-switched research network that became a root of the internet.'],
  ['ENIAC', 'An early general-purpose electronic computer, used for calculation at unprecedented speed.'],
  ['Zero', 'A symbol and place-value idea that made modern arithmetic and algebra practical.'],
])

export const RELATED = new Map([
  ['Transistor', ['Integrated circuit', 'Microprocessor', 'Personal computer']],
  ['Agriculture', ['Irrigation', 'Plough', 'Domestication of the sheep']],
  ['Writing', ['Papyrus', 'Paper', 'Printing press', 'Alphabet']],
  ['Steam engine', ['Railroad', 'Steamboat', 'Factory']],
  ['Internet', ['ARPANET', 'World Wide Web', 'Smartphone']],
  ['World Wide Web', ['Internet', 'Search engine', 'Smartphone']],
])
